!function(e){var r={};function t(o){if(r[o])return r[o].exports;var n=r[o]={i:o,l:!1,exports:{}};return e[o].call(n.exports,n,n.exports,t),n.l=!0,n.exports}t.m=e,t.c=r,t.d=function(e,r,o){t.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:o})},t.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},t.t=function(e,r){if(1&r&&(e=t(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(t.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)t.d(o,n,function(r){return e[r]}.bind(null,n));return o},t.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(r,"a",r),r},t.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},t.p="",t(t.s="./resources/views/theme/index.js")}({"./resources/views/theme/dark.js":
/*!***************************************!*\
  !*** ./resources/views/theme/dark.js ***!
  \***************************************/
/*! no static exports found */function(e,r,t){"use strict";Object.defineProperty(r,"__esModule",{value:!0}),r.default=void 0;r.default={name:"dark",text:"#E6E4EB",bg:"#2D2D2D",previewColor:"#F3F2F5",input:{background:"#373737",color:"#F3F2F5",border:"#454545",borderActive:"#1384FF"},button:{color:"#F3F2F5",bgColor:"rgba(255,255,255,0.25)",border:"#636363",bgActive:"rgba(255,255,255,0.10)"},secondaryButton:{borderColor:"#636363",textColor:"#F3F2F5"},CTAButton:{bgColor:"#1384FF",textColor:"#fff",bgActive:"#0F72DB"},radio:{selectedColor:"#1384FF",border:"#1384FF"}}},"./resources/views/theme/index.js":
/*!****************************************!*\
  !*** ./resources/views/theme/index.js ***!
  \****************************************/
/*! no static exports found */function(e,r,t){"use strict";Object.defineProperty(r,"__esModule",{value:!0}),r.default=void 0;var o=u(t(/*! ./dark */"./resources/views/theme/dark.js")),n=u(t(/*! ./light */"./resources/views/theme/light.js"));function u(e){return e&&e.__esModule?e:{default:e}}r.default=function(e){return"dark"===e?o.default:n.default}},"./resources/views/theme/light.js":
/*!****************************************!*\
  !*** ./resources/views/theme/light.js ***!
  \****************************************/
/*! no static exports found */function(e,r,t){"use strict";Object.defineProperty(r,"__esModule",{value:!0}),r.default=void 0;r.default={name:"light",text:"#747474",bg:"#F7F7F7",previewColor:"#242424",input:{background:"#FBFBFB",color:"#505050",border:"#E4E4E4",borderActive:"#1384FF"},button:{color:"#505050",bgColor:"#FBFBFB",border:"#E4E4E4",bgActive:"#F3F2F5"},secondaryButton:{borderColor:"#B2AEBD",textColor:"#817B8F"},CTAButton:{bgColor:"#1384FF",textColor:"#fff",bgActive:"#0F72DB"},radio:{selectedColor:"#969696",border:"#969696"}}}});